### ISSUE TITLE
Failed while building

### ISSUE THREAD

**Issue by quochung2310** [TinkerTools/tinker#120]
Hi!
I am using openSuse Tumbleweed.
I downloaded gzip from this link: [https://dasher.wustl.edu/tinker/downloads/tinker-8.10.2.tar.gz](url)
Following step stated in this link: [https://www.webmo.net/support/tinker7_linux.html](url)
At the step 4: compile Tinker: `Sudo make`
I got this:
`gfortran -Ofast -mssse3 -fopenmp -static-libgcc -o alchemy.x -L. -L/usr/local/tinker/lib/macos -L/usr/local/tinker/fftw/lib alchemy.o libtinker.a -lfftw3_threads -lfftw3 ; strip alchemy.x
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: libtinker.a(fft3d.o): in function `fftsetup_':
fft3d.f:(.text+0x37b): undefined reference to `dfftw_init_threads_'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: fft3d.f:(.text+0x385): undefined reference to `dfftw_plan_with_nthreads_'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: fft3d.f:(.text+0x3af): undefined reference to `dfftw_plan_dft_3d_'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: fft3d.f:(.text+0x3d9): undefined reference to `dfftw_plan_dft_3d_'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: libtinker.a(fft3d.o): in function `fftclose_':
fft3d.f:(.text+0xf5e): undefined reference to `dfftw_destroy_plan_'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: fft3d.f:(.text+0xf68): undefined reference to `dfftw_destroy_plan_'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: libtinker.a(fft3d.o): in function `fftfront_':
fft3d.f:(.text+0x990): undefined reference to `dfftw_execute_dft_'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: libtinker.a(fft3d.o): in function `fftback_':
fft3d.f:(.text+0xef0): undefined reference to `dfftw_execute_dft_'
collect2: error: ld returned 1 exit status
strip: 'alchemy.x': No such file
make: *** [Makefile:793: alchemy.x] Error 1
`
Any suggestion please?
Alos, I am newbie to Linux :-(
Thank you very much!

**Comment by jayponder** [comment]
Hi, Please don't use the "dasher.wustl.edu" version, as it is older. Get the current GitHub repo from https://github. com/TinkerTools/tinker, and let me know if you have trouble building that version.

The errors you are seeing above are because you are missing the FFTW libraries needed to build Tinker. You will either need to build the FFTW libraries prior to building Tinker. Alternatively prebuilt FFTW libraries for various GNU compiler versions under Linux are supplied with the GitHub repo, so you may not need to do the FFTW build.
