### ISSUE TITLE
N-terminal proline with "H2N" cap built with `protein` has two Hs on the N.

### ISSUE THREAD

**Issue by CanisW** [TinkerTools/tinker#128]
Pretty much what the title says. When I built a peptide with `H2N` as the N-term cap and proline as the first residue at N-teminal, the built structure had two hydrogens on the proline's nitrogen,  making the N-term charged. Technically, It is not wrong since the cap is named "H2N" indicating two Hs. But as to me, when it comes to assignment of the type of ternimals, My first thought would expect a neutral terminal with one H instead of a charged terminal with two Hs. I'm not sure if the two Hs is the intended behavior or not. If so, I was wondering if there's a way to build proline with neutral N-terminal. Thanks!

**Comment by jayponder** [comment]
Thanks! As you note, this is a "bug", of sorts. I agree the PROTEIN program should build a neutral PRO residue when you specify H2N as the N-terminal capping group (even though for the case of an N-terminal PRO it's actually HN instead of H2N).

To my knowledge this has never come up before, which is maybe a little surprising. I should be able to fix it without too much trouble. But this is also kind of a moot point as I think none of the force fields Tinker currently supports will have parameters for this kind of neutral N-terminal PRO.

I'll post again here once I've had a chance to patch this and get the fix pushed to GitHub.

**Comment by pren** [comment]
Yanxing is generating multipoles for these residues because they are in the "dipeptides" of the ANI database.

**Comment by jayponder** [comment]
OK, this is now patched. The N-terminal H2N cap for a PRO residue will only put one hydrogen on the terminal nitrogen. The patch is pushed to GitHub. So the PROTEIN program behaves "correctly".

I would note that XYZPDB and PDBXYZ can still get confused by these neutral "H2N" caps, and may be missing a proton or convert the residue back into a standard protonated N-terminal residues.
