### ISSUE TITLE
Wrong number in oplsaa.prm file

### ISSUE THREAD

**Issue by mircodaniel** [TinkerTools/tinker#152]
In the 435th and 445th line of oplsaa.prm file the last numbers are entered incorrectly:
atom        383   20    OS    "DiMe Phosphate CH3-O"         8    15.999    1
atom        393   20    OS    "Me MePhosphonate CH3-O"       8    15.999    1

The last numbers have to be two instead of one.

**Comment by jayponder** [comment]
Thank you for the correction. In addition to the two atom types you mention (383 and 393), also atom type 388 should have two instead of one as the number of attachments.

This has been corrected in the master sources, and will appear in the next commit of Tinker. In the meantime, please just change these entries in your oplsaa.prm file.
