### ISSUE TITLE
echarge2.f PME charge-charge does not include reciprocal space

### ISSUE THREAD

**Issue by nabraham47** [TinkerTools/Tinker#42]
We found for organic crystals, the vibrate executable computes non-physical vibrations. We expect the vibration to be 3 zero wavenumbers and 3*N-3 positive wavenumbers (where N is the number of atoms). Instead, the current version produces negative wavenumbers on the magnitude of -5 to -100 cm^-1. 

If a finite difference approach is implemented using echarge1.f the issue is resolved. We have verified that the results with this fix match those of the numerical Hessian using testhess. We have our own implementation of the fix that we would be happy to share, but it has not been tested to assure it won't cause issues for executables other than vibrate.

**Comment by jayponder** [comment]
This is a known issue. To our knowledge, there is no existing analytical Hessian for PME electrostatics at the present time (though people are reported to be working on this). Adding a finite difference Hessian, as noted by the poster, will solve the problem and will also obviously agree with the numerical Hessian in TESTHESS since that numerical Hessian is also just evaluated by finite differences. A slightly more efficient approach than suggested in the original post is to compute the analytical Hessian for the real space PME interactions, which is relatively easy, and then use finite differences for just the reciprocal space portion. This approach is taken in the current version of Tinker (ie, 8.5)-- the real space Hessian is implemented, but the finite difference reciprocal space portion based on ecrecip1.f is not yet implemented. We will finish this version in the future, instead of adopting the full finite difference method suggested in the original post.
