### ISSUE TITLE
Segfault when using poledit

### ISSUE THREAD

**Issue by corinwagen** [TinkerTools/Tinker#59]
Hello, 

I installed Tinker 8.7.2 yesterday and am attempting to follow [these directions](https://sites.google.com/site/amoebaworkshop/exercise-2#TOC-AMOEBA-parameterisation-schematic) for parameterizing a new molecule with the AMOEBA force field. Unfortunately, when I try and call `poledit` I get a segmentation fault (tried about 5 times). I think that the `gdmaout` file is being read correctly, since information populates. I'm using the ``amoeba09.prm`` file that came with the distribution when prompted by ``poledit``.

I was trying this on H2 for simplicity. 

```
Local Frame Intergroup Induced Dipole Moments (Debye) :

    Atom              X           Y           Z         Total

       1           0.0000      0.0000      0.1312      0.1312
       2           0.0000      0.0000     -0.1312      0.1312

 Condense Symmetric Atoms to Equivalent Types [Y] :  Y

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x5605BD
#1  0x54C270
#2  0x2B3B4334D27F
#3  0x408B69
#4  0x41704B
#5  0x402A0C
#6  0x2B3B433393D4
#7  0x404CAC
Segmentation fault (core dumped)
$ which gfortran
/n/sw/eb/apps/centos7/GCCcore/8.3.0/bin/gfortran
$ which gcc
/n/sw/eb/apps/centos7/GCCcore/8.3.0/bin/gcc
```

My ``.gdmaout`` file is attached. 

Thanks! 

[mp2.gdmaout.txt](https://github.com/TinkerTools/Tinker/files/4695253/mp2.gdmaout.txt)

**Comment by jayponder** [comment]
Hi, You must have gotten Tinker 8.7.2 from the Ponder group web site. It is from November 2019, and many changes have been made in Tinker since then. Get Tinker from the repo here on Github, which is Tinker 8.8. The bug you mention is fixed in the current Github version. Generally, the Ponder group web site lags a few months behind the TinkerTools Github repo. Sorry you hit on a bug. Dihydrogen seems like it should be a simple test, but it's actually a bit of a special case...

**Comment by corinwagen** [comment]
Thanks! I'll build the latest version and try again.
