### ISSUE TITLE
Non standard residue

### ISSUE THREAD

**Issue by jokurian** [TinkerTools/tinker#68]
Hi,
I am writing this here since I could not find the forum for TINKER.
How can we change the parameter file so that a non standard residue can also used? Consider a case in which there is a bond between two standard residues. 

 My aim is to do QM/MM dynamics with SHARC. So I am using the tinker 6.3.3 coming with OpenMolcas.

Thanks and Regards,
Jo

**Comment by jayponder** [comment]
I'm sorry to bring bad news, but..

I'm guessing by "residue" you mean amino acid residue? It is a very large amount of work to add a new amino acid type throughout Tinker. So much so that probably nobody will do it. Your best way forward is to just use the standard residue closest to the non-standard one that you want, and then manually edit the resulting .xyz file to add/delete atoms to convert the standard residue into your non-standard one. This procedure would only generate the coordinates file. You would, of course, also need to find or invent the force field parameters needed for you non-standard residue in whatever force field you are using, such as Amber, CHARMM, etc.

I would also note that Tinker 6.3.3 is nearly 8 years old, and is really no longer supported by the Tinker developers.

There is no active "forum" for Tinker. If you have questions or want more detail, please email me directly at ponder@dasher.wustl.edu

**Comment by bdw2292** [comment]
Hello,

You can try using https://github.com/pren/poltype/tree/poltype2 , Poltype2. There is an example called ModifiedAminoAcid in the Examples folder. Please read the docs for more information and let me know if you have any trouble or questions. 

One frequent issue I find with people using this module, is inconsistencies between PDB structure and PDB atom labels in the input file, so be careful about how you assign protonation states and modify your PDB file. 

- Brandon Walker

**Comment by bdw2292** [comment]
Also, I realize the current example online is just for single modified
amino acid. I believe I have an example somewhere between two amino acids,
I will try to find this and add to Examples folder.
