### ISSUE TITLE
poledit frame assignment error

### ISSUE THREAD

**Issue by walkerbdev** [TinkerTools/tinker#71]
[9_8_Index_0-peditin.txt](https://github.com/TinkerTools/tinker/files/5525290/9_8_Index_0-peditin.txt)
[9_8_Index_0.sdf.txt](https://github.com/TinkerTools/tinker/files/5525291/9_8_Index_0.sdf.txt)
[9_8_Index_0.gdmaout.txt](https://github.com/TinkerTools/tinker/files/5525294/9_8_Index_0.gdmaout.txt)

Hello, I noticed the hydrogens on the benzene in this molecule were assigned multipole frames of ions. Poltype relies on poledit defaults now instead of making our own in the input peditin.txt file. 

Thanks for your time,

- Brandon Walker

**Comment by bdw2292** [comment]
[9_8_Index_0.key.txt](https://github.com/TinkerTools/tinker/files/5525303/9_8_Index_0.key.txt)

Output key file

**Comment by bdw2292** [comment]
[9_8_Index_0.xyz.txt](https://github.com/TinkerTools/tinker/files/5525389/9_8_Index_0.xyz.txt)
Okay it would seem that sometimes 3 cycles of OPT are not long enough sometimes, we have H bonds of 1.2,

**Comment by jayponder** [comment]
Hi Brandon, Since POLEDIT works only from the DMA output, it has to decide when atoms are close enough to be "bonded". The tolerances currently used are based on scaled covalent radii for each element. At present, for example, a carbon and hydrogen have to be 1.2615 Ang or closer to be considered bonded. If you have C-H bonds in a molecule that are longer than that, then I'd say your structure is not very good, and you probably can't trust the DMA values from QM on such a bad structure!

If you want, I can perhaps loosen the tolerances a bit more, but I think the current values are probably very good. If you make the distance tolerance much bigger then you start to pick up inappropriate things as bonds, which causes POLEDIT problems as well. I do not know of any C-H bond length in a real organic molecule that is greater than 1.26 Ang.

If you are OK with the current settings, then I'll close this. You guys need to be careful to do enough QM optimization to get reasonable structures. I would guess that a small number of QM optimization cycles should generally be fine, but that asusmes your input structure already has at least reasonable (ie, not "crazy") bond and angle values.

**Comment by bdw2292** [comment]
Yes, sounds very reasonable, thank you! We will attend to this optimization issue very soon.
________________________________
