### ISSUE TITLE
angle unit change

### ISSUE THREAD

**Issue by pren** [TinkerTools/tinker#89]
Jay,
Do your changes to angle & torsion unit from degree to radian affect the parameter files? The restraint constants are apparently inconsistent now between latest and older tinker.

**Comment by zjing7** [comment]
I compared it with the older version, only restraints are affected. "angle" unit has been using radian; "torsion" unit is the same as energy.

**Comment by jayponder** [comment]
I believe all the code and parameter files in the current Tinker distribution are correct-- I was very careful in making this change for obvious reasons. I thought I had notified you guys, J-P and Louis, the Qubit folks, etc. The changes apply to Tinker8 and Tinker9. And I personally made the corresponding changes in Tinker-HP. There are many internal changes in the energy routines, and changes to some of the "XXXunit" variables that scale force field energy/gradient values.

The Tinker code now has radians in the force constants for any term that uses linear/harmonic/etc.-based force constants. These would include angle and torsion restraints, and many force field potential terms including: angle, stretch-bend, angle-torsion, improper (CHARMM) torsion, and charge flux angle component. All of these now use radians internally. Radians are also used in the actual force constant values in the parameter files, unless the force field developer (Allinger, CHARMM, etc.) uses other units in their published parameters. In the latter case, Tinker uses the XXXunit variables to convert to radians internally.

There were several reasons for making this change: (1) the previous versions Tinker used degrees in some force constants and radians in others with no logical pattern, (2) the conversion to radians puts the force constant values on a similar level for distances (via Angstroms) and angles (via radians) since Angstroms and radians are similarly large units, and (3) most of the rest of the world and other modeling packages have tended to converge on using radians.

In particular, you will need to be careful with angle restraints such as the "Boresch restraint" stuff, with torsion restraints you may be using the POLTYPE torsion fitting, and with charge flux angle force constants in AMOEBA+.
